"""
risk_engine.py
==============

Core SwapGuard risk-decision layer.

This module sits BEHIND the REST API. It:
1. Loads the trained SwapGuard hybrid model bundle.
2. Converts incoming engineered telemetry into the exact training feature schema.
3. Produces:
   - Isolation Forest anomaly score
   - Random Forest fraud probability
   - Hybrid ML score
4. Evaluates transparent telecom-security policy rules.
5. Returns an explainable final risk decision.

It does NOT implement HTTP endpoints. A FastAPI/Spring Boot layer should call
SwapGuardRiskEngine.evaluate(...).

IMPORTANT:
- Thresholds and policy rules below are prototype defaults.
- They must be validated/calibrated using authorized carrier or pilot data before
  any production use.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional

import joblib
import numpy as np
import pandas as pd


DEFAULT_MODEL_PATH = "models/swapguard_hybrid_bundle.joblib"

LOW_TO_MEDIUM_THRESHOLD = 0.55
MEDIUM_TO_HIGH_THRESHOLD = 0.80


@dataclass
class RiskAssessment:
    risk_score: float
    risk_band: str
    recommended_action: str

    anomaly_score: float
    supervised_fraud_probability: float
    hybrid_ml_score: float
    policy_floor: float

    risk_drivers: List[str]
    policy_rules_triggered: List[str]

    model_version: str = "swapguard-community-hybrid-v0.1"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class SwapGuardRiskEngine:
    """
    Explainable hybrid risk engine for pre-SIM-swap decision support.

    Expected telemetry fields correspond to the engineered fields generated by
    generate_dataset.py, for example:

        tenure_days_since_activation
        swap_age_hours
        device_velocity_count_7d
        originating_channel
        channel_bot_score
        auth_silent_possession_failed
        roaming_country_mismatch
        ...

    The engine aligns those fields to the exact encoded schema saved during
    training, so the inference feature order cannot drift from model training.
    """

    def __init__(self, model_path: str = DEFAULT_MODEL_PATH) -> None:
        self.model_path = Path(model_path)

        if not self.model_path.exists():
            raise FileNotFoundError(
                f"SwapGuard model bundle not found at '{self.model_path}'. "
                "Run the hybrid model training pipeline first."
            )

        bundle = joblib.load(self.model_path)

        required_bundle_keys = {
            "isolation_forest",
            "random_forest",
            "feature_names",
            "source_feature_columns",
            "categorical_features",
            "training_medians",
            "iforest_calibration",
            "hybrid_supervised_weight",
            "hybrid_anomaly_weight",
            "hybrid_threshold",
        }

        missing = required_bundle_keys - set(bundle.keys())
        if missing:
            raise KeyError(
                "The SwapGuard model bundle is missing required metadata: "
                + ", ".join(sorted(missing))
            )

        self.isolation_forest = bundle["isolation_forest"]
        self.random_forest = bundle["random_forest"]

        self.feature_names: List[str] = list(bundle["feature_names"])
        self.source_feature_columns: List[str] = list(
            bundle["source_feature_columns"]
        )
        self.categorical_features: List[str] = list(
            bundle["categorical_features"]
        )

        self.training_medians: Dict[str, float] = dict(
            bundle["training_medians"]
        )

        self.iforest_calibration: Dict[str, float] = dict(
            bundle["iforest_calibration"]
        )

        self.hybrid_supervised_weight = float(
            bundle["hybrid_supervised_weight"]
        )
        self.hybrid_anomaly_weight = float(
            bundle["hybrid_anomaly_weight"]
        )
        self.hybrid_threshold = float(bundle["hybrid_threshold"])

        self.model_metadata = {
            "synthetic_fraud_rate": bundle.get("synthetic_fraud_rate"),
            "benchmark_results": bundle.get("benchmark_results"),
            "random_state": bundle.get("random_state"),
        }

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def evaluate(self, telemetry: Mapping[str, Any]) -> Dict[str, Any]:
        """
        Evaluate one pre-swap telemetry record and return an explainable result.
        """
        normalized = self._derive_missing_flags(dict(telemetry))
        X = self._build_model_vector(normalized)

        anomaly_score = self._calculate_anomaly_score(X)
        supervised_probability = self._calculate_supervised_probability(X)

        hybrid_ml_score = (
            self.hybrid_supervised_weight * supervised_probability
            + self.hybrid_anomaly_weight * anomaly_score
        )

        policy = self._evaluate_policy_rules(normalized)

        # Policy rules do not blindly add arbitrary points to the ML output.
        # Instead, strong telecom-security combinations can establish a minimum
        # risk floor. This keeps policy behavior transparent and auditable.
        final_score = max(hybrid_ml_score, policy["policy_floor"])
        final_score = float(np.clip(final_score, 0.0, 1.0))

        risk_band, recommended_action = self._decision(
            final_score=final_score,
            critical_policy=policy["critical_policy"],
        )

        drivers = self._collect_risk_drivers(
            telemetry=normalized,
            anomaly_score=anomaly_score,
            supervised_probability=supervised_probability,
            policy_drivers=policy["risk_drivers"],
        )

        assessment = RiskAssessment(
            risk_score=round(final_score, 4),
            risk_band=risk_band,
            recommended_action=recommended_action,
            anomaly_score=round(anomaly_score, 4),
            supervised_fraud_probability=round(
                supervised_probability, 4
            ),
            hybrid_ml_score=round(hybrid_ml_score, 4),
            policy_floor=round(policy["policy_floor"], 4),
            risk_drivers=drivers,
            policy_rules_triggered=policy["rules_triggered"],
        )

        return assessment.to_dict()

    # ------------------------------------------------------------------
    # Feature preparation
    # ------------------------------------------------------------------
    def _derive_missing_flags(
        self,
        telemetry: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Derive binary flags from raw/continuous fields when they are omitted.

        This makes the engine easier to call from an API while preserving the
        training feature contract.
        """

        if "tenure_is_new_line_30d" not in telemetry:
            tenure = self._safe_float(
                telemetry.get("tenure_days_since_activation")
            )
            if tenure is not None:
                telemetry["tenure_is_new_line_30d"] = int(tenure <= 30)

        swap_age = self._safe_float(telemetry.get("swap_age_hours"))
        if swap_age is not None:
            telemetry.setdefault(
                "swap_is_swapped_in_window",
                int(swap_age > 0),
            )
            telemetry.setdefault(
                "swap_is_very_recent_24h",
                int(0 < swap_age <= 24),
            )
            telemetry.setdefault(
                "swap_is_recent_7d",
                int(0 < swap_age <= 168),
            )

        device_velocity = self._safe_float(
            telemetry.get("device_velocity_count_7d")
        )
        if device_velocity is not None:
            telemetry.setdefault(
                "device_velocity_high_flag",
                int(device_velocity >= 3),
            )

        imei_count = self._safe_float(
            telemetry.get("imei_shared_msisdn_count")
        )
        if imei_count is not None:
            telemetry.setdefault(
                "imei_is_shared_across_numbers",
                int(imei_count > 1),
            )

        geo_distance = self._safe_float(
            telemetry.get("geo_mno_to_home_distance_km")
        )
        if geo_distance is not None:
            telemetry.setdefault(
                "geo_inconsistency_flag",
                int(geo_distance > 100.0),
            )

        channel = str(telemetry.get("originating_channel", "")).strip()
        if channel:
            telemetry.setdefault(
                "channel_is_automated",
                int(channel in {"chatbot", "rpa_api", "ivr"}),
            )

        bot_score = self._safe_float(telemetry.get("channel_bot_score"))
        if bot_score is not None:
            telemetry.setdefault(
                "channel_is_high_risk_bot",
                int(bot_score >= 0.80),
            )

        contact_days = self._safe_float(
            telemetry.get("profile_days_since_contact_change")
        )
        if contact_days is not None:
            telemetry.setdefault(
                "profile_contact_changed_recently_7d",
                int(contact_days <= 7),
            )

        silent_passed = telemetry.get("auth_silent_possession_passed")
        silent_failed = telemetry.get("auth_silent_possession_failed")

        if silent_passed is not None and silent_failed is None:
            telemetry["auth_silent_possession_failed"] = int(
                not bool(silent_passed)
            )

        if silent_failed is not None and silent_passed is None:
            telemetry["auth_silent_possession_passed"] = int(
                not bool(silent_failed)
            )

        roaming_active = telemetry.get("roaming_is_active")
        if roaming_active is not None:
            telemetry.setdefault("roaming_country_mismatch", 0)

        return telemetry

    def _build_model_vector(
        self,
        telemetry: Mapping[str, Any],
    ) -> pd.DataFrame:
        """
        Convert one telemetry record into the exact one-hot encoded feature
        schema used during training.
        """
        record: Dict[str, Any] = {}

        # Build raw source feature row.
        for feature in self.source_feature_columns:
            if feature == "originating_channel":
                record[feature] = str(
                    telemetry.get(feature, "unknown")
                ).strip()
                continue

            value = telemetry.get(feature)

            if value is None:
                # Missing numeric source values are left NaN and imputed using
                # training medians after encoding.
                record[feature] = np.nan
            else:
                record[feature] = value

        frame = pd.DataFrame([record])

        frame = pd.get_dummies(
            frame,
            columns=self.categorical_features,
            prefix="channel",
            dtype=int,
        )

        # Align to the exact training feature order.
        frame = frame.reindex(
            columns=self.feature_names,
            fill_value=0,
        )

        frame = frame.replace([np.inf, -np.inf], np.nan)

        # Apply training-only medians saved with the model bundle.
        for feature in self.feature_names:
            if frame[feature].isna().any():
                median = self.training_medians.get(feature, 0.0)
                frame[feature] = frame[feature].fillna(median)

        return frame.astype(float)

    # ------------------------------------------------------------------
    # Model scoring
    # ------------------------------------------------------------------
    def _calculate_anomaly_score(
        self,
        X: pd.DataFrame,
    ) -> float:
        raw_score = float(
            self.isolation_forest.decision_function(X)[0]
        )

        q_low = float(self.iforest_calibration["q_low"])
        q_high = float(self.iforest_calibration["q_high"])

        if q_high <= q_low:
            raise ValueError(
                "Invalid Isolation Forest calibration metadata."
            )

        risk = 1.0 - ((raw_score - q_low) / (q_high - q_low))
        return float(np.clip(risk, 0.0, 1.0))

    def _calculate_supervised_probability(
        self,
        X: pd.DataFrame,
    ) -> float:
        probability = float(
            self.random_forest.predict_proba(X)[0, 1]
        )
        return float(np.clip(probability, 0.0, 1.0))

    # ------------------------------------------------------------------
    # Transparent policy layer
    # ------------------------------------------------------------------
    def _evaluate_policy_rules(
        self,
        telemetry: Mapping[str, Any],
    ) -> Dict[str, Any]:
        """
        Evaluate explainable telecom-risk rules.

        Policy floors are prototype values. They are intentionally separated
        from the ML model and should be calibrated with operator policy and
        empirical pilot evidence before production use.
        """
        rules_triggered: List[str] = []
        risk_drivers: List[str] = []

        policy_floor = 0.0
        critical_policy = False

        silent_failed = self._flag(
            telemetry,
            "auth_silent_possession_failed",
        )
        recent_profile_change = self._flag(
            telemetry,
            "profile_contact_changed_recently_7d",
        )
        very_recent_swap = self._flag(
            telemetry,
            "swap_is_very_recent_24h",
        )
        recent_swap = self._flag(
            telemetry,
            "swap_is_recent_7d",
        )
        new_device = self._flag(
            telemetry,
            "device_is_new_imei",
        )
        geo_mismatch = self._flag(
            telemetry,
            "geo_inconsistency_flag",
        )
        high_velocity = self._flag(
            telemetry,
            "device_velocity_high_flag",
        )
        shared_imei = self._flag(
            telemetry,
            "imei_is_shared_across_numbers",
        )
        high_bot = self._flag(
            telemetry,
            "channel_is_high_risk_bot",
        )
        automated_channel = self._flag(
            telemetry,
            "channel_is_automated",
        )
        roaming_mismatch = self._flag(
            telemetry,
            "roaming_country_mismatch",
        )
        new_line = self._flag(
            telemetry,
            "tenure_is_new_line_30d",
        )

        # Strong multi-signal rules.
        if silent_failed and recent_profile_change:
            rules_triggered.append(
                "RULE_POSSESSION_FAILURE_PLUS_PROFILE_CHANGE"
            )
            risk_drivers.extend(
                [
                    "SILENT_AUTH_FAILED",
                    "RECENT_PROFILE_CHANGE",
                ]
            )
            policy_floor = max(policy_floor, 0.80)

        if silent_failed and high_bot:
            rules_triggered.append(
                "RULE_POSSESSION_FAILURE_PLUS_HIGH_AUTOMATION"
            )
            risk_drivers.extend(
                [
                    "SILENT_AUTH_FAILED",
                    "HIGH_AUTOMATION_SCORE",
                ]
            )
            policy_floor = max(policy_floor, 0.85)
            critical_policy = True

        if very_recent_swap and new_device and geo_mismatch:
            rules_triggered.append(
                "RULE_RECENT_SWAP_NEW_DEVICE_GEO_MISMATCH"
            )
            risk_drivers.extend(
                [
                    "VERY_RECENT_SIM_CHANGE",
                    "NEW_DEVICE",
                    "GEOGRAPHIC_INCONSISTENCY",
                ]
            )
            policy_floor = max(policy_floor, 0.82)

        if high_velocity and shared_imei:
            rules_triggered.append(
                "RULE_DEVICE_VELOCITY_PLUS_IMEI_SHARING"
            )
            risk_drivers.extend(
                [
                    "HIGH_DEVICE_VELOCITY",
                    "MULTI_LINE_DEVICE_ASSOCIATION",
                ]
            )
            policy_floor = max(policy_floor, 0.80)

        if automated_channel and recent_profile_change and new_line:
            rules_triggered.append(
                "RULE_AUTOMATION_PROFILE_CHANGE_NEW_LINE"
            )
            risk_drivers.extend(
                [
                    "AUTOMATED_REQUEST_CHANNEL",
                    "RECENT_PROFILE_CHANGE",
                    "LOW_ACCOUNT_TENURE",
                ]
            )
            policy_floor = max(policy_floor, 0.78)

        if roaming_mismatch and geo_mismatch:
            rules_triggered.append(
                "RULE_ROAMING_AND_LOCATION_MISMATCH"
            )
            risk_drivers.extend(
                [
                    "ROAMING_COUNTRY_MISMATCH",
                    "GEOGRAPHIC_INCONSISTENCY",
                ]
            )
            policy_floor = max(policy_floor, 0.72)

        # Moderate single/paired controls establish smaller floors.
        if silent_failed:
            risk_drivers.append("SILENT_AUTH_FAILED")
            policy_floor = max(policy_floor, 0.58)

        if high_bot:
            risk_drivers.append("HIGH_AUTOMATION_SCORE")
            policy_floor = max(policy_floor, 0.58)

        if recent_swap and recent_profile_change:
            rules_triggered.append(
                "RULE_RECENT_SWAP_PLUS_PROFILE_CHANGE"
            )
            risk_drivers.extend(
                [
                    "RECENT_SIM_CHANGE",
                    "RECENT_PROFILE_CHANGE",
                ]
            )
            policy_floor = max(policy_floor, 0.68)

        return {
            "policy_floor": float(policy_floor),
            "critical_policy": bool(critical_policy),
            "rules_triggered": self._deduplicate(rules_triggered),
            "risk_drivers": self._deduplicate(risk_drivers),
        }

    # ------------------------------------------------------------------
    # Explainability / decisioning
    # ------------------------------------------------------------------
    def _collect_risk_drivers(
        self,
        telemetry: Mapping[str, Any],
        anomaly_score: float,
        supervised_probability: float,
        policy_drivers: Iterable[str],
    ) -> List[str]:
        drivers = list(policy_drivers)

        if anomaly_score >= 0.80:
            drivers.append("HIGH_BEHAVIORAL_ANOMALY")
        elif anomaly_score >= 0.65:
            drivers.append("ELEVATED_BEHAVIORAL_ANOMALY")

        if supervised_probability >= 0.80:
            drivers.append("HIGH_KNOWN_PATTERN_FRAUD_PROBABILITY")
        elif supervised_probability >= 0.60:
            drivers.append("ELEVATED_KNOWN_PATTERN_FRAUD_PROBABILITY")

        if self._flag(telemetry, "device_is_new_imei"):
            drivers.append("NEW_DEVICE")

        if self._flag(telemetry, "geo_inconsistency_flag"):
            drivers.append("GEOGRAPHIC_INCONSISTENCY")

        if self._flag(telemetry, "tenure_is_new_line_30d"):
            drivers.append("LOW_ACCOUNT_TENURE")

        if self._flag(telemetry, "device_velocity_high_flag"):
            drivers.append("HIGH_DEVICE_VELOCITY")

        if self._flag(
            telemetry,
            "imei_is_shared_across_numbers",
        ):
            drivers.append("MULTI_LINE_DEVICE_ASSOCIATION")

        return self._deduplicate(drivers)

    def _decision(
        self,
        final_score: float,
        critical_policy: bool,
    ) -> tuple[str, str]:
        if critical_policy:
            return "HIGH", "HOLD_OR_MANUAL_REVIEW"

        if final_score >= MEDIUM_TO_HIGH_THRESHOLD:
            return "HIGH", "HOLD_OR_MANUAL_REVIEW"

        if final_score >= LOW_TO_MEDIUM_THRESHOLD:
            return "MEDIUM", "STEP_UP_AUTHENTICATION"

        return "LOW", "ALLOW_WITH_STANDARD_CONTROLS"

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------
    @staticmethod
    def _safe_float(value: Any) -> Optional[float]:
        if value is None:
            return None

        try:
            return float(value)
        except (TypeError, ValueError):
            return None

    @staticmethod
    def _flag(
        telemetry: Mapping[str, Any],
        name: str,
    ) -> bool:
        value = telemetry.get(name, 0)

        if isinstance(value, str):
            return value.strip().lower() in {
                "1",
                "true",
                "yes",
                "y",
            }

        return bool(value)

    @staticmethod
    def _deduplicate(values: Iterable[str]) -> List[str]:
        seen = set()
        result = []

        for value in values:
            if value not in seen:
                seen.add(value)
                result.append(value)

        return result


if __name__ == "__main__":
    # Example only. Replace with telemetry from your adapter/API layer.
    engine = SwapGuardRiskEngine()

    example_request = {
        "tenure_days_since_activation": 14,
        "swap_age_hours": 10,
        "device_velocity_count_7d": 4,
        "imei_shared_msisdn_count": 3,
        "device_is_new_imei": 1,
        "geo_mno_to_home_distance_km": 420.0,
        "originating_channel": "chatbot",
        "channel_bot_score": 0.91,
        "profile_days_since_contact_change": 2,
        "auth_silent_possession_passed": 0,
        "roaming_is_active": 1,
        "roaming_country_mismatch": 1,
    }

    result = engine.evaluate(example_request)

    print("\n🛡️ SwapGuard Risk Assessment")
    print("============================")
    for key, value in result.items():
        print(f"{key}: {value}")
